# Generated by Django 3.1.3 on 2022-07-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
