# Generated by Django 3.1.3 on 2022-07-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('work', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('assignDate', models.DateTimeField(auto_now=True, null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.department')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
