# Generated by Django 3.1.3 on 2022-08-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('workCompleted', models.CharField(max_length=100, null=True)),
                ('updationDate', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('taskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.task')),
            ],
        ),
    ]
