# Generated by Django 3.1.3 on 2022-08-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_tasktracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracking',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
